%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \\wsl.localhost\ubuntu-22.04\home\joseph\code\astrolib\sat1.txt
%
% Auto-generated by MATLAB on 10-Jan-2024 00:20:14

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "x", "y", "z", "vx", "vy", "vz", "q1", "q2", "q3", "q4", "om1", "om2", "om3"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
sat1 = readtable("\\wsl.localhost\ubuntu-22.04\home\joseph\code\astrolib\sat1.txt", opts);


%% Clear temporary variables
clear opts